# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/hydrangea/project/AMD/bad_apple_7020_lcd/bad_apple_7020_lcd.srcs/sources_1/bd/top_bd/ip/top_bd_processing_system7_0_0/top_bd_processing_system7_0_0.xci
# IP: The module: 'top_bd_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hydrangea/project/AMD/bad_apple_7020_lcd/bad_apple_7020_lcd.gen/sources_1/bd/top_bd/ip/top_bd_processing_system7_0_0/top_bd_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_bd_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/hydrangea/project/AMD/bad_apple_7020_lcd/bad_apple_7020_lcd.srcs/sources_1/bd/top_bd/ip/top_bd_processing_system7_0_0/top_bd_processing_system7_0_0.xci
# IP: The module: 'top_bd_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hydrangea/project/AMD/bad_apple_7020_lcd/bad_apple_7020_lcd.gen/sources_1/bd/top_bd/ip/top_bd_processing_system7_0_0/top_bd_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_bd_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
