# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# Block Designs: bd/top_bd/top_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_bd || ORIG_REF_NAME==top_bd} -quiet] -quiet

# IP: bd/top_bd/ip/top_bd_processing_system7_0_0/top_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_bd_processing_system7_0_0 || ORIG_REF_NAME==top_bd_processing_system7_0_0} -quiet] -quiet

# XDC: /home/hydrangea/project/AMD/bad_apple_7020_lcd/bad_apple_7020_lcd.gen/sources_1/bd/top_bd/top_bd_ooc.xdc
