domain_path: D:\Projects\prj\AMD\bad_apple_7020_lcd\worksapce_new\platform\export\platform\sw\standalone_ps7_cortexa9_0
app_src_dir: D:\AMD\Vitis\2024.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
